language: julia

os:
  - linux

julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly

addons:
  apt:
    packages:
    - hdf5-tools

# script:
#   - julia --color=yes -e 'using Pkg; Pkg.build()'
#   - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test(coverage=true)'
script:
    - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.add(PackageSpec(name="DistributedFactorGraphs", rev="jt/develop")); Pkg.build(); Pkg.test(coverage=true)'

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("IncrementalInference")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
