language: julia

os:
  - linux

arch:
  - amd64
  - arm64

julia:
  - 1.0
  - 1.2
  - 1.3
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
    - julia: nightly
    - arch: arm64

jobs:
  fast_finish: true

addons:
  apt:
    packages:
    - hdf5-tools
    - texlive-latex-base
    - texlive-pictures
    - preview-latex-style
    - dot2tex

before_script:
  - if [ `arch` == x86_64 ]; then pip install dot2tex; fi

# script:
#   - julia --color=yes -e 'using Pkg; Pkg.build()'
#   - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test(coverage=true)'
#TEMP test with DFG master until 0.6 is tagged
script:
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; Pkg.add(PackageSpec(name="DistributedFactorGraphs", rev="master")); Pkg.build(); Pkg.test(coverage=true)'

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("IncrementalInference")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
